name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: PEP 8 Check
        run: flake8 app.py
        continue-on-error: true

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t bence309/bence309-petproject:latest .
          docker push bence309/bence309-petproject:latest
